/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve a URL and list candidate pages
         * @description Resolves the host (a site may only serve `www`, so follow `rootUrl`, not the string you sent) and lists same-origin pages from the sitemap, or the homepage's links as a fallback.
         */
        post: operations["discover"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enqueue a crawl
         * @description Validates the URL at the edge (a bad URL is a 422, no job queued) and enqueues a crawl. Poll `/crawl/{jobId}/result`, or pass a `callbackUrl` to be notified. Page URLs must be absolute and same-origin; a relative or absent `pages` list falls back to a breadth-first walk from the root (capped at `MAX_CRAWL_PAGES = 10`).
         */
        post: operations["enqueueCrawl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/{jobId}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job status and raw crawl result */
        get: operations["getCrawlResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/{jobId}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The full audit for a completed crawl
         * @description The design-token inventory, contrast findings, and summary. A `409` until the crawl finishes.
         */
        get: operations["getAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/{jobId}/typography": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Typography inventory only */
        get: operations["getTypography"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crawl/{jobId}/colours": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Colour clusters only */
        get: operations["getColours"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface webhooks {
    crawlFinished: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crawl completed or failed
         * @description Same payload as the per-request `callbacks` above; see `/crawl`.
         */
        post: operations["crawlFinishedWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export interface components {
    schemas: {
        Error: {
            /** @description A human-readable message. */
            error: string;
        };
        DiscoveredPage: {
            /** Format: uri */
            url: string;
            /** @example /pricing */
            path: string;
            title: string;
        };
        DiscoverResult: {
            /**
             * Format: uri
             * @description The resolved origin. Follow this, not the input.
             */
            rootUrl: string;
            host: string;
            /**
             * @description How pages were found, from a sitemap or homepage anchors (fallback).
             * @enum {string}
             */
            via?: "sitemap" | "links";
            pages: components["schemas"]["DiscoveredPage"][];
        };
        CrawlRequest: {
            /** @example https://picocss.com/ */
            url: string;
            /**
             * @description Absolute, same-origin page URLs to crawl. Capped at 10.
             * @example [
             *       "https://picocss.com/",
             *       "https://picocss.com/docs"
             *     ]
             */
            pages?: string[];
            /** @description Page ceiling for the BFS fallback. Clamped to [1, 10]. */
            maxPages?: number;
            /**
             * Format: uri
             * @description Public http(s) endpoint to POST the finished audit to. SSRF-guarded (loopback/private/link-local refused unless allowlisted via `DRIFT_WEBHOOK_ALLOWED_HOSTS`) and validated at enqueue time.
             */
            callbackUrl?: string;
        };
        JobResult: {
            /** @enum {string} */
            status: "queued" | "active" | "completed" | "failed";
            /** @description The raw crawl result once completed; null otherwise. */
            result?: components["schemas"]["CrawlResult"] | null;
            /** @description Present when status is `failed` (e.g. a crawl that reached zero pages). */
            error?: string;
        };
        CrawlResult: {
            /** Format: uri */
            rootUrl: string;
            /** Format: date-time */
            crawledAt: string;
            pages: {
                /** Format: uri */
                url?: string;
                title?: string;
                elementCount?: number;
            }[];
        };
        /** @description Headline counts for the audit. */
        AuditSummary: {
            pages?: number;
            distinctColours?: number;
            colourFamilies?: number;
            /** @description Colours within ~2 ΔE of another (genuine redundancy). */
            colourNearDuplicates?: number;
            fontFamilies?: number;
            typeSizes?: number;
            fontWeights?: number;
            /** @description Type sizes off the closest modular scale. */
            typeOffScale?: number;
            spacings?: number;
            /** @description Spacing values off a 4px grid. */
            spacingOffGrid?: number;
            radii?: number;
            radiusNearDuplicates?: number;
            shadows?: number;
            /** @description Distinct text/background pairs evaluated. */
            contrastPairs?: number;
            /** @description Pairs failing WCAG AA for normal text. */
            contrastFailingAA?: number;
        };
        ContrastFinding: {
            foreground?: string;
            background?: string;
            ratio?: number;
            passAA?: boolean;
            passAAA?: boolean;
            passAALarge?: boolean;
            /** @description Text elements using this exact pair. */
            count?: number;
            sampleTags?: string[];
            /** @description Pages this pair appears on. */
            pages?: string[];
        };
        /** @description The full audit. `summary` and `contrast` are the machine-friendly headline; the inventory arrays carry every deduplicated token in use, attributed to the pages it appears on. */
        SiteAudit: {
            /** Format: uri */
            rootUrl: string;
            summary: components["schemas"]["AuditSummary"];
            /** @description Colour families with swatches, usage and near-duplicate relations. */
            colourFamilies?: Record<string, never>[];
            /** @description Families, roles, sizes, weights, line-heights, letter-spacings. */
            typography?: Record<string, never>;
            spacing?: Record<string, never>[];
            radius?: Record<string, never>[];
            shadow?: Record<string, never>[];
            borders?: Record<string, never>[];
            opacity?: Record<string, never>[];
            zIndex?: Record<string, never>[];
            blur?: Record<string, never>[];
            gradients?: Record<string, never>[];
            motion?: Record<string, never>;
            breakpoints?: Record<string, never>[];
            /** @description How the site authors its tokens: units and value strings per category, plus its own custom properties. */
            authored?: Record<string, never>;
            /** @description Text/background pairs with their WCAG verdict, worst first. */
            contrast?: components["schemas"]["ContrastFinding"][];
        };
        WebhookEvent: {
            /** @constant */
            event: "crawl.completed";
            jobId: string;
            /** Format: uri */
            site: string;
            audit: components["schemas"]["SiteAudit"];
        } | {
            /** @constant */
            event: "crawl.failed";
            jobId: string;
            /** Format: uri */
            site: string;
            error: string;
        };
    };
    responses: never;
    parameters: {
        /** @description The id returned by `POST /crawl`. */
        JobId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    discover: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description A URL or bare host. Absolute or `example.com` both work.
                     * @example picocss.com
                     */
                    url: string;
                };
            };
        };
        responses: {
            /** @description Resolved origin and candidate pages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverResult"];
                };
            };
            /** @description `url` is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid, unreachable, or non-http(s) URL, with a human-readable message. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    enqueueCrawl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrawlRequest"];
            };
        };
        responses: {
            /** @description Crawl accepted; poll or await the webhook. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 24 */
                        jobId: string;
                    };
                };
            };
            /** @description `url` is missing. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unusable URL or invalid `callbackUrl` (validated at enqueue time). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getCrawlResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id returned by `POST /crawl`. */
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The job's status, and the raw crawl result once completed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResult"];
                };
            };
            /** @description No such job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAudit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id returned by `POST /crawl`. */
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The audit. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteAudit"];
                };
            };
            /** @description No such job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The crawl has not finished (never a 200 all-zeros audit). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getTypography: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id returned by `POST /crawl`. */
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic typography inventory derived from the completed crawl. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description No such job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The crawl has not finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getColours: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The id returned by `POST /crawl`. */
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perceptually clustered colours with usage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        clusters?: Record<string, never>[];
                        clusterCount?: number;
                        distinctColours?: number;
                    };
                };
            };
            /** @description No such job. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The crawl has not finished. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    crawlFinishedWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["WebhookEvent"];
            };
        };
        responses: {
            /** @description Acknowledged. */
            "2XX": {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
